SELECT length(COMPANY_ID), COMPANY_ID   FROM db_cars.factorys;

SELECT COUNT(*) AS CNT FROM FACTORYS;

INSERT INTO factorys
(COMPANY_ID, COMPANY)
value
('car-01', 'AUDI');

UPDATE FACTORYS
SET COMPANY = '페라리'
WHERE COMPANY_ID = 'car-01' ;

DELETE FROM factorys
WHERE COMPANY_ID = 'car-01' ;

SELECT * FROM FACTORYS
WHERE COMPANY_ID = 'car-01';