
CREATE TABLE CAR_COMPANY
(
  COMPANY_NAME   VARCHAR(50) NOT NULL COMMENT '회사이름',
  CAR_COMPANY_ID VARCHAR(50) NOT NULL COMMENT '차회사_ID',
  PRIMARY KEY (CAR_COMPANY_ID)
) COMMENT '차회사';

CREATE TABLE CARS
(
  CAR_NAME       VARCHAR(50) NOT NULL COMMENT '자동차이름',
  CARS_ID        VARCHAR(50) NOT NULL COMMENT 'CARS_ID',
  CAR_COMPANY_ID VARCHAR(50) NOT NULL COMMENT '차회사_ID'
) COMMENT '차';

CREATE TABLE CARS_OPTIONS
(
  OPTIONS_ID     VARCHAR(50) NOT NULL COMMENT '옵션_ID',
  CAR_COMPANY_ID VARCHAR(50) NOT NULL COMMENT '차회사_ID'
) COMMENT '차 옵션';

CREATE TABLE OPTIONS_CODE
(
  OPTIONS_ID VARCHAR(50) NOT NULL COMMENT '옵션코드_ID',
  'OPTION'   VARCHAR(50) NOT NULL COMMENT '옵션',
  PRIMARY KEY (OPTIONS_ID)
) COMMENT '옵션코드';

CREATE TABLE YEARS_CODE
(
  YEARS          INTEGER     NOT NULL COMMENT '연식',
  YEARS_CODE_ID  VARCHAR(50) NOT NULL COMMENT '연식_ID',
  CAR_COMPANY_ID VARCHAR(50) NOT NULL COMMENT '차회사_ID',
  PRIMARY KEY (YEARS_CODE_ID)
) COMMENT '연식코드';

ALTER TABLE CARS_OPTIONS
  ADD CONSTRAINT FK_OPTIONS_CODE_TO_CARS_OPTIONS
    FOREIGN KEY (OPTIONS_ID)
    REFERENCES OPTIONS_CODE (OPTIONS_ID);

ALTER TABLE YEARS_CODE
  ADD CONSTRAINT FK_CAR_COMPANY_TO_YEARS_CODE
    FOREIGN KEY (CAR_COMPANY_ID)
    REFERENCES CAR_COMPANY (CAR_COMPANY_ID);

ALTER TABLE CARS
  ADD CONSTRAINT FK_CAR_COMPANY_TO_CARS
    FOREIGN KEY (CAR_COMPANY_ID)
    REFERENCES CAR_COMPANY (CAR_COMPANY_ID);

ALTER TABLE CARS_OPTIONS
  ADD CONSTRAINT FK_CAR_COMPANY_TO_CARS_OPTIONS
    FOREIGN KEY (CAR_COMPANY_ID)
    REFERENCES CAR_COMPANY (CAR_COMPANY_ID);
