
CREATE TABLE ADRESS_CODE
(
  ADRESS      VARCHAR(50) NOT NULL COMMENT '주소',
  ADRESS_CODE VARCHAR(50) NOT NULL COMMENT '주소_ID',
  PRIMARY KEY (ADRESS_CODE)
) COMMENT '주소코드';

CREATE TABLE GENDER_CODE
(
  GENDER      VARCHAR(50) NOT NULL COMMENT '성별',
  GENDER_CODE VARCHAR(50) NOT NULL COMMENT '성별_ID',
  PRIMARY KEY (GENDER_CODE)
) COMMENT '성별코드';

CREATE TABLE HOBBY_CODE
(
  NOBBY_CODE_ID VARCHAR(50) NOT NULL COMMENT '유니크_ID',
  HOBBY         VARCHAR(50) NOT NULL COMMENT '취미명',
  PRIMARY KEY (NOBBY_CODE_ID)
) COMMENT '취미코드';

CREATE TABLE MEMBERS
(
  NAME        VARCHAR(50) NOT NULL COMMENT '이름',
  AGE         INTEGER     NOT NULL COMMENT '나이',
  PHONENUMBER VARCHAR(50) NOT NULL COMMENT '전화번호',
  MEMBERS_ID  VARCHAR(50) NOT NULL COMMENT '유니크_ID',
  GENDER_CODE VARCHAR(50) NOT NULL COMMENT '성별_ID',
  ADRESS_CODE VARCHAR(50) NOT NULL COMMENT '주소_ID',
  PRIMARY KEY (MEMBERS_ID)
) COMMENT '회원정보';

CREATE TABLE MEMBERS_HOBBY
(
  MEMBERS_ID    VARCHAR(50) NOT NULL COMMENT '유니크_ID',
  NOBBY_CODE_ID VARCHAR(50) NOT NULL COMMENT '유니크_ID'
) COMMENT '회원_취미';

CREATE TABLE MEMBERS_LOGIN
(
  EMAIL            VARCHAR(50) NOT NULL COMMENT '이메일',
  MEMBERS_ID       VARCHAR(50) NOT NULL COMMENT '유니크_ID',
  MEMBERS_LOGIN_ID VARCHAR(50) NOT NULL COMMENT '회원_로그인 ID',
  PRIMARY KEY (MEMBERS_LOGIN_ID)
) COMMENT '회원_로그인';

ALTER TABLE MEMBERS_LOGIN
  ADD CONSTRAINT FK_MEMBERS_TO_MEMBERS_LOGIN
    FOREIGN KEY (MEMBERS_ID)
    REFERENCES MEMBERS (MEMBERS_ID);

ALTER TABLE MEMBERS_HOBBY
  ADD CONSTRAINT FK_MEMBERS_TO_MEMBERS_HOBBY
    FOREIGN KEY (MEMBERS_ID)
    REFERENCES MEMBERS (MEMBERS_ID);

ALTER TABLE MEMBERS_HOBBY
  ADD CONSTRAINT FK_HOBBY_CODE_TO_MEMBERS_HOBBY
    FOREIGN KEY (NOBBY_CODE_ID)
    REFERENCES HOBBY_CODE (NOBBY_CODE_ID);

ALTER TABLE MEMBERS
  ADD CONSTRAINT FK_GENDER_CODE_TO_MEMBERS
    FOREIGN KEY (GENDER_CODE)
    REFERENCES GENDER_CODE (GENDER_CODE);

ALTER TABLE MEMBERS
  ADD CONSTRAINT FK_ADRESS_CODE_TO_MEMBERS
    FOREIGN KEY (ADRESS_CODE)
    REFERENCES ADRESS_CODE (ADRESS_CODE);
